// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetapp.Models;

namespace dotnetapp.Migrations
{
    [DbContext(typeof(FitnessTrackerDbContext))]
    partial class FitnessTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dotnetapp.Models.FitnessTracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(50)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<decimal>("Distance_km")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<decimal>("SleepDuration")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<int>("Steps")
                        .HasColumnType("int");

                    b.Property<DateTime>("Workout_Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("FitnessTracker");
                });
#pragma warning restore 612, 618
        }
    }
}
